version: '3.4'
services:

  controller-usuario:
    image: incommerce/controllers/usuario:latest
    build:
      context: .
      dockerfile: controller.usuario/Dockerfile
    container_name: incommerce_controller_usuario
    ports:
      - "8080:80"
    environment:
      MYSQL_CONNECTION: "server=localhost;port=3306;database=dbloja;uid=root;password=123456"
